### PR TITLE
Updating Docusaurus version for documentation website

### LINKED ISSUE #1141: Update Docusaurus dependency for documentation website
The documentation website is currently using a beta version of Docusaurus (v2). V2 of Docusaurus has now exited beta and been released. https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0

There is a new feature (https://docusaurus.io/docs/markdown-features/code-blocks#custom-magic-comments) which will be useful for #1134 so it would be a good time to update the dependency to the latest release.

### PR DESCRIPTION
**Pull request by SlicedSilver**
**Type of PR:** enhancement

**Updating Docusaurus version for the documentation website to the latest version.**

The documentation website was using a beta version of Docusaurus (v2.0.0-beta.17) and this pull request brings it up to the release version of 2.0.1.

Updating Docusaurus unlocks a few new features which will be useful for #1134 and #1135

Closes #1141

### CODE REVIEW

**Comment by romfrancois** [comment]
Dont see any objections in approving & merging this one.
@eugene-korobko, @kirchet any comments?

**Comment by kirchet** [comment]
> Dont see any objections in approving & merging this one. @eugene-korobko, @kirchet any comments?

Looks good for me, but we need to fix the pipeline 🙂

**Comment by SlicedSilver** [comment]
**To fix the pipeline:**
1. Make the `build` job require the completion of the `install-deps-website` job (in addition to `install-deps`).
2. Bump required node version from `16.3.1` to `16.14`.
---

**Item 1)** The `tsc-verify` task is expecting the docusaurus tsconfig file to be installed already. Thus we need to only run the `build` job after both the `install-deps` and `install-reps-website` jobs have run.
https://github.com/tradingview/lightweight-charts/blob/4daa902167fcac8341d0bb4f45a5648f56eec2af/.circleci/config.yml#L293-L296

**Item 2)** Docusaurus build complains if the node version is less than `16.14`. Can we bump the Node version up to `16.14`?
FYI: Release notes for Node v16.14: https://nodejs.org/en/blog/release/v16.14.0/

Would need to change the following:
https://github.com/tradingview/lightweight-charts/blob/4daa902167fcac8341d0bb4f45a5648f56eec2af/.circleci/config.yml#L43-L45
to:
`- image: circleci/node:16.14` 

which would install node 16.14.2 as mentioned here: https://circleci.com/developer/images/image/cimg/node

Additionally we would need to update the version numbers mentioned in `package.json`, `building.md`

@kirchet Do these changes look correct?

**Comment by kirchet** [comment]
> Do these changes look correct?

Yes. But probably we need to merge #1143 first and then bump version to `18.6.5`. Or even bump this version in #1143.

**Comment by SlicedSilver** [comment]
> Yes. But probably we need to merge #1143 first and then bump version to `18.6.5`. Or even bump this version in #1143.

Agreed, that it would be better to first merge #1144. 

Are we happy to jump to `18.6.5` rather than updating to the minimum required version of `16.14`? If so, the latest 'current' node version is `18.7.0`. Should we use `18.7.0`?

If we are happy to proceed to update Node, then I'll make the changes to the #1143 pull request. Including: updating circleCI version, `@types/node`, `package.json`, and `building.md`.

**Comment by kirchet** [comment]
> Are we happy to jump to 18.6.5 rather than updating to the minimum required version of 16.14?

Yes

> If so, the latest 'current' node version is 18.7.0. Should we use 18.7.0?

I don't think that there are a lot of differences, but it's better to keep in sync the version of Node everywhere where it possible. So, if we're using `@types/node": "~18.6.5` we should use `18.6.5` everywhere.

**Comment by SlicedSilver** [comment]
@romfrancois @kirchet
Tested this PR again with Node 16.16 and the recent merge. Should be good to go.

The `dts-changes` CI test fails but is expected because there was a typo fix for the jsdoc in this PR. 
Diff for your reference: https://output.circle-artifacts.com/output/job/42bd57fb-27e0-49cf-b8fe-f827f43995ab/artifacts/0/dts-changes/changes.diff

**Review by romfrancois — APPROVED** [review]

**Pull request merged**
