### PR TITLE
add `paneSize` getter to IChartApi

### PR DESCRIPTION
**Pull request by SlicedSilver**
**Type of PR:** enhancement

**PR checklist:**

- `N/A` ~Addresses an existing issue~
- [ ] Includes tests
- [x] Documentation update

**Overview of change:**

Adds a `paneSize` method to the IChartApi which returns the dimensions of the chart pane (the area excluding the time and price scales) where the actual series rendering takes place.

This is useful for Plugin development because there isn't an easy way to determine the pane height from the API, and you typically need to either use some `getBoundingClientRect` call, or get the height within the renderer scope.

### CODE REVIEW

**Comment by edew** [comment]
The d.ts changes are expected 

```
+/**
+ * Dimensions of the Chart Pane
+ * (the main chart area which excludes the time and price scales).
+ */
+export interface PaneSize {
+       /** Height of the Chart Pane (pixels) */
+       height: number;
+       /** Width of the Chart Pane (pixels) */
+       width: number;
+}
```

**Review by edew — DISMISSED** [review]

**Comment by skdillon** [comment]
Any updates on this merging? This is a prereq to closing #1407

**Comment by SlicedSilver** [comment]
> Any updates on this merging? This is a pre req to closing #1407 I think

@skdillon This is unrelated. This PR just adds a method for reading the paneSize. This isn't useful for any existing use cases and we are adding it for one of our upcoming features. (plugins support)

We do plan on merging this but it wouldn't solve your existing issue.

**Review by 0220tiezo1323 — CHANGES_REQUESTED** [review]
No

**Review by edew — APPROVED** [review]

**Pull request merged**
