### PR TITLE
Cloud Area Chart

### PR DESCRIPTION
**Pull request by mastermobin**
Nowadays, Ichimoku Cloud is an inseparable part of our technical analyses, so I implemented it for myself in last 2 days.

I think this PR could be useful for many people using this precious library.

Thank you.

### CODE REVIEW

**Comment by mastermobin** [comment]
Are there problems for merging this feature? (Any bugs or something like that, which I could fix) :thinking:

**Comment by timocov** [comment]
Hi @mastermobin, sorry for late reply.

First of all, thanks for your interest and contribution in lightweight-charts.

I do understand why and where it might be useful, but I'm not sure that it should be done in this way. This is exactly why we put "Outside contributors may implement enhancement/features only after an approval (label "help wanted") by Lightweight Charts project maintainers" in our [contribution guide](https://github.com/tradingview/lightweight-charts/blob/master/CONTRIBUTING.md#pull-requests). The closest feature request for this PR it seems is #140 which has a "need proposal" label what means that we need to discuss API first to be sure that everything is covered.

I don't think that we need to create another series type for that (#140). _Perhaps_ that it might be done more easier via adding something like "series linking" which allows you set 2 series to link to and colors rather than adding a new series type.

If you'd like to continue with this feature, I'd suggest to continue a discussion (to start from the beginning 🙂) in the issue or create a new GitHub Discussion to chat about this feature's API (probably some part of your code might be applied as-is with the new approach).

What do you think?

**Comment by mastermobin** [comment]
I'm in :D. 
I'm Ok with either continuing discussion in the issue or creating a new Github discussion.

**Comment by timocov** [comment]
@mastermobin I'm sorry for late reply. I just created a discussion https://github.com/tradingview/lightweight-charts/discussions/714.

**Pull request closed without merging**
