### PR TITLE
Fixed incorrect timestamp locale format

### PR DESCRIPTION
**Pull request by YaoKaiLun**
**Type of PR:** bugfix

**PR checklist:**

fixes # https://github.com/tradingview/lightweight-charts/issues/221

### CODE REVIEW

**Comment by YaoKaiLun** [comment]
Does it be supported in 3.0? I cannot use it by npm.

**Comment by timocov** [comment]
It will be available in 3.0, which is still in development. You can subscribe on releases via github so you be notified when the new release happened though.

**Comment by YaoKaiLun** [comment]
> It will be available in 3.0, which is still in development. You can subscribe on releases via github so you be notified when the new release happened though.

Thanks a lot, but i am anxious to fix this problem, is there any other method i can do to handle this situation?

**Comment by timocov** [comment]
Even if I merged this PR it doesn't help you until we publish the new version. Right now it seems that it's impossible to override it in 2.0.0, but you can correct your times to add an offset to them with timezone you'd like to have).

**Pull request closed without merging**
