### PR TITLE
correct calculations for fixLeftEdge and fixRightEdge case on the fir…

### LINKED ISSUE #1356: Bug: `fix*Edge` does not render properly on first render
**Lightweight Charts™ Version:** 4.0.1

**Steps/code to reproduce:**

Looks like the `fixLeftEdge` and `fixRightEdge` are broking the first render

**Actual behavior:**

On first render the chart is empty, with data in it actually, but is just not visible.
If user somehow interacts with the chart (click on it, drags, zooms, resizes the browser tab) the chart becomes visible

First render: 
image

**Expected behavior:**

Be visible on first render too

(After user drags on the chart)
image

**CodeSandbox/JSFiddle/etc link:**

https://stackblitz.com/edit/react-ts-oee6az?file=package.json,App.tsx,index.tsx

### PR DESCRIPTION
**Pull request by signatenkov**
…st render

**Type of PR:** bugfix

**PR checklist:**

- [ ] Addresses an existing issue: fixes #1356

### CODE REVIEW

**Comment by signatenkov** [comment]
@SlicedSilver hey, will it automatically run graphics tests? i can't run them locally due to puppeteer error

**Comment by SlicedSilver** [comment]
> @SlicedSilver hey, will it automatically run graphics tests? i can't run them locally due to puppeteer error

It will run automatically when the branch is pushed to GitHub

The `memleaks` test is broken on master at the moment. So it is good to cancel it (otherwise it will time-out anyway).

**Comment by signatenkov** [comment]
@SlicedSilver Do you have any questions here? All tests are passing meaning this change doesn't introduce regression. I wonder if it make sense to add graphics test (on v4 branch) to cover this particular edge case....

**Comment by SlicedSilver** [comment]
> I wonder if it make sense to add graphics test (on v4 branch) to cover this particular edge case....

Yes, if you could please add a graphics test 🙏
Ideally any change or bugfix which can affect the rendering of the chart should have a graphics test case.

**Comment by signatenkov** [comment]
@SlicedSilver Can't agree more! Will do shortly.

**Pull request merged**
