### PR TITLE
New type of Markers: Icons

### PR DESCRIPTION
**Pull request by Flydexo**
**Type of PR:** enhancement

Before creating a complete pull request with tests and the documentation update. I just wanted to know if you agree with this feature.

### CODE REVIEW

**Comment by timocov** [comment]
> Before creating a complete pull request with tests and the documentation update. I just wanted to know if you agree with this feature.

Interesting approach to ask whether we agree with this feature by implementing it and providing a PR 😄 

@Flydexo do have examples how it looks like with different images?

**Comment by Flydexo** [comment]
Yep there you go
market cap dark
btc candle dark
btc candle white
market cap white

**Comment by Flydexo** [comment]
Yep there you go
market cap dark
btc candle dark
btc candle white
market cap white

**Comment by Flydexo** [comment]
Code example:
`{time: Math.round(date/1000), position: "aboveBar", shape: "icon", size: 5, id: a.id, image: logo}`

**Comment by Flydexo** [comment]
@timocov

**Comment by fillky** [comment]
This would be nice to have, any updates on this?

**Comment by romfrancois** [comment]
Hi @Flydexo!

Apologies for missing this one out :(
Would you mind rebasing your PR and making sure it compiles OK? 
We would then review it and check if everything is fine before merging it.

**Comment by aliasmac** [comment]
Any updates on this being merged in? @timocov @Flydexo 🙏

**Comment by edew** [comment]
As Romain's last comment mentions the merge conflicts would need to be solved first.

Some graphics tests should also be added I think.

Once those two things are done we can start a proper review.

**Review by 0220tiezo1323 — CHANGES_REQUESTED** [review]
No

**Comment by SlicedSilver** [comment]
Thank you for your feature PR for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this feature should be implemented as a plugin instead, and will be closing this PR as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature as a plugin will greatly benefit both you and the Lightweight Charts community.

**Pull request closed without merging**
