### PR TITLE
Docs: Customisation Guide and ‘How To’ Examples

### LINKED ISSUE #1134: Documentation: Guided Tutorial - Customisation
**Purpose:** Provide a simple walkthrough which showcases how to customise Lightweight Charts to the user’s requirements.  

Essentially, a step by step guide which explains to the reader where and how to apply the customisations options. The user should follow along on their IDE and end up with the same finished output (building up as they go along). (Each section would carry on from the previous section and progress towards the final result.)

_Note:_ The reader would be expect to first read the `Getting Started` section of the documentation site. Thus it wouldn't need to cover / repeat everything included there.

The walkthrough will start with a standard line chart and describe how to customise the following (simple changes so the tutorial is quick and easy to follow):
- [x]  Colours
- [x]  Price Scale
- [x]  Time Scale
- [x]  Price Line

Page contents:
* Each page will have code blocks, and an embedded chart of the result.
* Each section will have a link to a complete run-able code example (on JSFiddle or something similar).
* Links to the referenced APIs

### LINKED ISSUE #1135: Documentation: How To (Snippets / Examples)
The lightweight charts website ([Lightweight Financial Charting Library — TradingView](https://www.tradingview.com/lightweight-charts/)) has a great selection of examples showcasing how to implement various features, such as: tooltips, range selectors, legends.

A section could be added to the documentation site containing short explanations of how to implement these features. This makes the examples: 
1. easier to find for more users (who may not visit the website but go straight to the documentation site), and 
2. easier to find via a search engine.

These pages can be short and sweet depending on each example. For example,  `How to invert a price scale` would be very short because it just needs to reference the `invertScale` property on the priceScale and show a small code sample. Where as, `How to add a legend` would require a bit more explanation.

**Each page would include:**
* The example embedded with a JSFiddle link to the full source code.
* Code blocks containing the key parts of the example.
* Links to APIs and Options relevant to the current example.

**A tentative list of pages to be added:**
How to…
- [ ]  ...add a custom legend,
- [ ]  ...adjust the range (implement a range selector),
- [ ]  ...add a tooltip,
- [ ]  ...add a watermark,
- [ ]  ...invert a price scale,
- [ ]  ...add a price line (with title),
- [ ]  ...add series markers,
- [ ]  ...show two price scales,
- [ ]  ...show price and volume on a single chart.

### PR DESCRIPTION
**Pull request by SlicedSilver**
**Type of PR:** enhancement

**Overview of changes:**
* Add customisation guide to tutorials section.
* Add ‘how to’ examples to the tutorials section.
* Improved code block component to support: 
	* hiding and revealing lines, 
	* fading specific lines, and 
	* removing lines (but keeping in the copy clipboard).
* Added a warning banner for the tutorials page which only appears when user isn’t browsing the latest published version (since the tutorials section isn’t versioned yet).

**Preview Link**
https://gorgeous-florentine-dd67a1.netlify.app/lightweight-charts/tutorials

**Issues addressed:**
* Closes #1135
* Closes #1134

**Related issues:**
* We could potentially close this issue: #1002
* Watermark tutorial address this question: #774

### CODE REVIEW

**Comment by romfrancois** [comment]
LGTM ... didn't spot anything obvious so far.
All the example tested make sense and work as expected.

**Review by romfrancois — APPROVED** [review]

**Comment by edew** [comment]
Looks good - a couple of questions though @SlicedSilver:

1. When I run the site locally the examples for the tutorial don't load. Is there an extra step I need to run to get them working?

image

2. The expand/collapse animation is quite slow, at least on my machine. What do you think about removing the animation?

expandcollapse

**Comment by SlicedSilver** [comment]
> Looks good - a couple of questions though @SlicedSilver:
> 
> 1. When I run the site locally the examples for the tutorial don't load. Is there an extra step I need to run to get them working?
> 
> 2. The expand/collapse animation is quite slow, at least on my machine. What do you think about removing the animation?
> 

1. There are no extra steps required to build the site. It's an issue which only seems to occur when using `docusaurus serve`. The files are correctly generated, and the site works when hosted on a site or using a local web server like `python -m http.server`. I suspect that the docusaurus implementation of a server is doing something extra that's not on a typical server. Also it works in normal development mode (`npm run start`). I'll do a bit more digging into the docusaurus code to find the reason.

2. The animation time is very long because the revealed code block is very large (and the animation length is determined by the height). Currently using the built-in `details` component. I can swizzle the component to change the animation behaviour (or probably just apply a css rule).

**Comment by SlicedSilver** [comment]
> When I run the site locally the examples for the tutorial don't load. Is there an extra step I need to run to get them working?
>> ...
>> I suspect that the Docusaurus implementation of a server is doing something extra that's not on a typical server. 
>> ...

Answer: The docusaurus serve command is setting this option: https://github.com/vercel/serve-handler#cleanurls-booleanarray

https://github.com/facebook/docusaurus/blob/94067ce9305653a4534f23c96406ae7fe9e35837/packages/docusaurus/src/commands/serve.ts#L77

Which automatically strips `.html` from the end of any url. GH pages doesn't have this behaviour, so it works as expected on GH pages amongst others. 

I'm going to add a feature request to Docusaurus to enable this as an options flag.

**Comment by SlicedSilver** [comment]
Updated the PR to include an 'instant' details element which instantly reveals the complete code blocks instead of using the default animation.

Preview: https://gorgeous-florentine-dd67a1.netlify.app/lightweight-charts/tutorials/customization/chart-colors#complete-code

**Comment by romfrancois** [comment]
> Updated the PR to include an 'instant' details element which instantly reveals the complete code blocks instead of using the default animation.
> 
> Preview: https://gorgeous-florentine-dd67a1.netlify.app/lightweight-charts/tutorials/customization/chart-colors#complete-code

It's way better this way!

**Review by edew — APPROVED** [review]

**Pull request merged**
