### PR TITLE
Add series getDataRange()

### LINKED ISSUE #336: Get series data time range
**Is your feature request related to a problem? Please describe.**

From paulverheul on discord

>Hi all! Just a quick question ... what I'm trying to do is load a chart with the data for a day, and then load more data when users zoom out. In order to do this, I need the date/time for the left most chart boundary. Is there a way to get this? I expected the VisibleTimeRangeChange event would be of help, but that only return the time range of the data in the chart, not the time range of the complete chart.

**Describe the solution you'd like**

Add method `series.getDataRange()` to get most left (past) and right (recent) time from series data,
and the return value should be similar to `chart.timeScale().getVisibleRange()`

**Additional context**

### PR DESCRIPTION
**Pull request by SuperPenguin**
**Type of PR:** Enchancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #336
- [ ] Includes tests
- [ ] Documentation update

### CODE REVIEW

**Comment by timocov** [comment]
I'm very appreciate your contribution and will do my best to make it merged to master, but to avoid any kind of misunderstanding/disappointing while review it'd be so much better to spend a bit of time to confirm proposal first in the issue and then start working on it (see https://github.com/tradingview/lightweight-charts/blob/master/CONTRIBUTING.md#pull-requests). And again, I don't want to block/reject this or any other PR, I just want to make review process more comfortable for everyone.

**Comment by SuperPenguin** [comment]
After little bit of thought, the method doesn't have much use anyway, and I kinda misunderstood the actual issue, gonna close this PR and issue.

**Comment by timocov** [comment]
I hope that your decision to close the issue/PR wasn't based on my comment, as I didn't mean to offend you in any way.

**Comment by SuperPenguin** [comment]
It was a misunderstanding on my part no worries.

**Pull request closed without merging**
