### PR TITLE
make contributions easier via fully automating the dev setup.

### PR DESCRIPTION
**Pull request by nisarhassan12**
**Type of PR:** 

Hi.

I work for Gitpod. This PR adds gitpod config to the repo to make contributions easier for newcomers i.e with a single click it will launch a workspace and automatically:

- clone the `lightweight-charts` repo.
- install the dependencies.
- run `npm run tsc-watch`.

This can be helpful for beginners i.e they can start coding instantly without setting anything up.

You can give it a try on my fork of the repo via the following link:

https://gitpod.io/#https://github.com/nisarhassan12/lightweight-charts

This is how it looks:

image

**PR checklist:**

- [ ] Addresses an existing issue: fixes #
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by timocov** [comment]
Hi,

thanks for your interest in lightweight-charts!

I have several questions at the moment:

- what popular projects have/use this feature?
- what advantages this feature provides to both maintainers and contributors?
- how exactly this thing makes "contributions easier"? where that dev setup is set up? who use it/how much people use it?
- afaik `npm run tsc-watch` doesn't work well at the moment because of custom transformation :)

**Comment by nisarhassan12** [comment]
Thanks.

> what popular projects have/use this feature?

A lot of projects out there are already using Gitpod to simplify contributors/maintainers onboarding experience some of them are:

-  https://github.com/freeCodeCamp/freeCodeCamp
-  https://github.com/facebook/docusaurus
-  https://github.com/mozilla/pdf.js/
-  https://github.com/gatsbyjs/gatsby/
-  https://github.com/mobxjs/mobx/

a subset of them can be found at https://contribute.dev 

image

> what advantages this feature provides to both maintainers and contributors?

Anyone interested in contributing can start with a single click i.e they don't have to: clone the repo and then make sure that they have correct version of Node installed and then install the dependencies and then finally start coding in the editor, with Gitpod everything is automated with a single click.

This can be quite helpful for those contributors who are on slow internet connections or low end devices i.e Gitpod only takes up as much memory or computing power as a single browser tab(process) would which is a lot more efficent then running a Code Editor, Some Node tasks in a terminal and in some cases a web browser all at the same time. 

I had the experience of using a an old Laptop which would cease to function ocassionaly If I run VS Code, A Web Browser and Webpack together.

For maintainers, it allows them to review changes online without the need of switching contexts and so on i.e to review and test the changes you don't have to pull the code from the PR banch and then re-install the dependencies if the dependencies in the Prs were changed or updated.

With the Gitpod app installed you can enable comments like the following in the PRs:

image

see https://github.com/freeCodeCamp/freeCodeCamp/pull/40071 for instance.

> afaik npm run tsc-watch doesn't work well at the moment because of custom transformation :)

We can remove that and add if something else is required to be running while development.

> how exactly this thing makes "contributions easier"? 

I hope that the above answers this well.  Let me know if you have further questions.

> where that dev setup is set up? 

In the `.gitpod.yml` file https://github.com/nisarhassan12/lightweight-charts/blob/master/.gitpod.yml which will be included in the repo once the Pr is merged. The point is to keep the configuration versioned alongside your project (same as with a CI file).

> who use it/how much people use it?

We have around `200,000+` users though all of them are not contributors/maintainers. I think visting `https://contribute.dev` would give you a better idea of who uses Gitpod.

**Comment by timocov** [comment]
> A lot of projects out there are already using Gitpod to simplify contributors/maintainers onboarding experience some of them are:

Do you have any stats how many contributions were made using this tool in that repos? It seems that just "having gitpod config in the repo" have nothing with "users use gitpod to contribute to the projects"?

> This can be quite helpful for those contributors who are on slow internet connections or low-end devices i.e Gitpod only takes up as much memory or computing power as a single browser tab(process) would which is a lot more efficient than running a Code Editor, Some Node tasks in a terminal and in some cases a web browser all at the same time.

Yeah, makes sense.

> Anyone interested in contributing can start with a single click i.e they don't have to: clone the repo and then make sure that they have the correct version of Node installed and then install the dependencies and then finally start coding in the editor, with Gitpod everything is automated with a single click.

Is that something like https://github.com/features/codespaces, right?

Don't get me wrong, but for me the main concern is that I don't known who will support this file since no one from maintainers (and probably from contributors either) doesn't use Gitpod, so we can't be sure that everything is fine and "potential contributors" wouldn't have pain in ass while they will try to set the project up in Gitpod just because something won't work because of changes we've done previously, but didn't check Gitpod config. For me personally it might be a stopper to make a contribution at all if I'd prefer to use Gitpod for that.

**Comment by kevin71089** [comment]
> **Type of PR:**
> 
> Hi.
> 
> I work for Gitpod. This PR adds gitpod config to the repo to make contributions easier for newcomers i.e with a single click it will launch a workspace and automatically:
> 
> * clone the `lightweight-charts` repo.
> * install the dependencies.
> * run `npm run tsc-watch`.
> 
> This can be helpful for beginners i.e they can start coding instantly without setting anything up.
> 
> You can give it a try on my fork of the repo via the following link:
> 
> https://gitpod.io/#https://github.com/nisarhassan12/lightweight-charts
> 
> This is how it looks:
> 
> image
> 
> **PR checklist:**
> 
> * [ ]  Addresses an existing issue: fixes #
> * [ ]  Includes tests
> * [ ]  Documentation update
> 
> **Overview of change:**
> 
> **Is there anything you'd like reviewers to focus on?**

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Pull request closed without merging**
